// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.28;

import {MemeverseRegistrarAbstract} from "./MemeverseRegistrarAbstract.sol";
import {IMemeverseRegistrarAtLocal} from "../interfaces/IMemeverseRegistrarAtLocal.sol";
import {IMemeverseRegistrar, IMemeverseRegistrationCenter} from "../interfaces/IMemeverseRegistrar.sol";

/**
 * @title Local MemeverseRegistrar for deploying memecoin and registering memeverse
 */
contract MemeverseRegistrarAtLocal is IMemeverseRegistrarAtLocal, MemeverseRegistrarAbstract {
    uint256 public constant DAY = 24 * 3600;

    address public registrationCenter;

    constructor(address _owner, address _registrationCenter, address _memeverseLauncher, address _memeverseCommonInfo)
        MemeverseRegistrarAbstract(_owner, _memeverseLauncher, _memeverseCommonInfo)
    {
        registrationCenter = _registrationCenter;
    }

    /// @notice Quotes the center-chain registration fee for the local registrar path.
    /// @dev The local registrar does not perform a registrar-to-center LayerZero send, so `value` is ignored here.
    /// The returned fee only covers the registration center's outbound remote fan-out, if any.
    /// @param param Registration request to be submitted to the center.
    /// @param value Unused placeholder kept for interface compatibility with the omnichain registrar.
    /// @return lzFee Native fee required by the registration center.
    function quoteRegister(IMemeverseRegistrationCenter.RegistrationParam calldata param, uint128 value)
        external
        view
        override
        returns (uint256 lzFee)
    {
        value;
        uint64 endTime = uint64(block.timestamp + param.durationDays * DAY);
        uint64 unlockTime = endTime + uint64(param.lockupDays * DAY);
        IMemeverseRegistrar.MemeverseParam memory memeverseParam = IMemeverseRegistrar.MemeverseParam({
            name: param.name,
            symbol: param.symbol,
            uri: param.uri,
            desc: param.desc,
            communities: param.communities,
            uniqueId: uint256(keccak256(abi.encodePacked(param.symbol))),
            endTime: endTime,
            unlockTime: unlockTime,
            omnichainIds: param.omnichainIds,
            UPT: param.UPT,
            flashGenesis: param.flashGenesis
        });
        (lzFee,,) =
            IMemeverseRegistrationCenter(registrationCenter).quoteSend(param.omnichainIds, abi.encode(memeverseParam));
    }

    /// @notice Registers the memeverse on the local chain.
    /// @dev Only the registration center may call this entrypoint after symbol validation succeeds.
    /// @param param Fully expanded memeverse configuration generated by the registration center.
    function localRegistration(MemeverseParam calldata param) external override {
        require(msg.sender == registrationCenter, PermissionDenied());

        _registerMemeverse(param);
    }

    /// @notice Forwards a local registration request into the registration center.
    /// @dev `value` is the exact native fee forwarded into `MemeverseRegistrationCenter.registration(...)` so the
    /// center can pay for any outbound remote registration messages.
    /// @param param Registration request to submit.
    /// @param value Exact native fee forwarded to the registration center.
    function registerAtCenter(IMemeverseRegistrationCenter.RegistrationParam calldata param, uint128 value)
        external
        payable
        override
    {
        require(msg.value == value, IMemeverseRegistrationCenter.InvalidInput());
        IMemeverseRegistrationCenter(registrationCenter).registration{value: value}(param);
    }

    /// @notice Updates the registration center trusted by this registrar.
    /// @dev Only callable by the owner.
    /// @param _registrationCenter New registration center address.
    function setRegistrationCenter(address _registrationCenter) external override onlyOwner {
        require(_registrationCenter != address(0), ZeroAddress());

        registrationCenter = _registrationCenter;

        emit SetRegistrationCenter(_registrationCenter);
    }
}
