// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.28;

import {MemeverseRegistrarAbstract} from "./MemeverseRegistrarAbstract.sol";
import {IMemeverseRegistrarAtLocal} from "../interfaces/IMemeverseRegistrarAtLocal.sol";
import {IMemeverseRegistrar, IMemeverseRegistrationCenter} from "../interfaces/IMemeverseRegistrar.sol";

/**
 * @title Local MemeverseRegistrar for deploying memecoin and registering memeverse
 */
contract MemeverseRegistrarAtLocal is IMemeverseRegistrarAtLocal, MemeverseRegistrarAbstract {
    uint256 internal constant FIXED_LOCKUP_DURATION = 365 days;
    uint256 internal constant MAX_END_TIME = type(uint64).max - FIXED_LOCKUP_DURATION;

    address public registrationCenter;

    constructor(address _owner, address _registrationCenter, address _memeverseLauncher, address _memeverseCommonInfo)
        MemeverseRegistrarAbstract(_owner, _memeverseLauncher, _memeverseCommonInfo)
    {
        registrationCenter = _registrationCenter;
    }

    /// @notice Quotes the center-chain registration fee for the local registrar path.
    /// @dev The local registrar does not perform a registrar-to-center LayerZero send, so `value` is ignored here.
    /// The returned fee only covers the registration center's outbound remote fan-out, if any.
    /// @param param Registration request to be submitted to the center.
    /// @param value Unused placeholder kept for interface compatibility with the omnichain registrar.
    /// @return lzFee Native fee required by the registration center.
    function quoteRegister(IMemeverseRegistrationCenter.RegistrationParam calldata param, uint128 value)
        external
        view
        override
        returns (uint256 lzFee)
    {
        value;
        uint32[] memory omnichainIds = _deduplicate(param.omnichainIds);
        (,, uint192 currentNonce) = IMemeverseRegistrationCenter(registrationCenter).symbolRegistry(param.symbol);
        uint256 centerDay = IMemeverseRegistrationCenter(registrationCenter).DAY();
        uint256 endTimeRaw = block.timestamp + param.durationDays * centerDay;
        require(endTimeRaw <= MAX_END_TIME, IMemeverseRegistrationCenter.InvalidInput());

        uint64 endTime = uint64(endTimeRaw);
        uint64 unlockTime = uint64(endTimeRaw + FIXED_LOCKUP_DURATION);
        IMemeverseRegistrar.MemeverseParam memory memeverseParam = IMemeverseRegistrar.MemeverseParam({
            name: param.name,
            symbol: param.symbol,
            uri: param.uri,
            desc: param.desc,
            communities: param.communities,
            uniqueId: uint256(keccak256(abi.encodePacked(param.symbol, currentNonce + 1, param.UPT))),
            endTime: endTime,
            unlockTime: unlockTime,
            omnichainIds: omnichainIds,
            UPT: param.UPT,
            flashGenesis: param.flashGenesis
        });
        (lzFee,,) = IMemeverseRegistrationCenter(registrationCenter).quoteSend(omnichainIds, abi.encode(memeverseParam));
    }

    /// @notice Registers the memeverse on the local chain.
    /// @dev Only the registration center may call this entrypoint after symbol validation succeeds.
    /// @param param Fully expanded memeverse configuration generated by the registration center.
    function localRegistration(MemeverseParam calldata param) external override {
        require(msg.sender == registrationCenter, PermissionDenied());

        _registerMemeverse(param);
    }

    /// @notice Forwards a local registration request into the registration center.
    /// @dev `value` is the exact native fee forwarded into `MemeverseRegistrationCenter.registration(...)` so the
    /// center can pay for any outbound remote registration messages.
    /// @param param Registration request to submit.
    /// @param value Exact native fee forwarded to the registration center.
    function registerAtCenter(IMemeverseRegistrationCenter.RegistrationParam calldata param, uint128 value)
        external
        payable
        override
    {
        require(msg.value == value, IMemeverseRegistrationCenter.InvalidInput());
        IMemeverseRegistrationCenter(registrationCenter).registration{value: value}(param);
    }

    /// @notice Updates the registration center trusted by this registrar.
    /// @dev Only callable by the owner.
    /// @param _registrationCenter New registration center address.
    function setRegistrationCenter(address _registrationCenter) external override onlyOwner {
        require(_registrationCenter != address(0), ZeroAddress());

        registrationCenter = _registrationCenter;

        emit SetRegistrationCenter(_registrationCenter);
    }

    function _deduplicate(uint32[] calldata input) internal pure returns (uint32[] memory uniqueValues) {
        uint256 inputLength = input.length;
        if (inputLength == 0) return new uint32[](0);

        uint32[] memory temp = new uint32[](inputLength);
        uint256 uniqueCount;

        for (uint256 i = 0; i < inputLength; ++i) {
            bool found;
            for (uint256 j = 0; j < uniqueCount; ++j) {
                if (temp[j] == input[i]) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                temp[uniqueCount] = input[i];
                ++uniqueCount;
            }
        }

        uniqueValues = new uint32[](uniqueCount);
        for (uint256 i = 0; i < uniqueCount; ++i) {
            uniqueValues[i] = temp[i];
        }
    }
}
